dkht/urls.py
"""
URLS for dkht App.
"""
from django.conf.urls import include, url
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import EntryList, EntryCreate, EntryDetail, EntryUpdate, EntryDelete
from .views import TagList, Main, Contact
from .views import DataVizDetail, PaymentSuccess
from .views import ClimateScrapeCreate, ClimateScrapeResults, ClimateScrapeExport, ClimateScrapeAnnualMaxPrecip
from .stripe_payment import DonateCheckout

from markdownx import urls as markdownx

app_name = 'dkht'

urlpatterns = [
    path('', Main.as_view(), name="main-view"),
    path('contact/', Contact.as_view(), name="contact-view"),
    path('markdownx/', include(markdownx)),
    path('projects/', EntryList.as_view(), name="entry-list"),
    path('create_entry/', EntryCreate.as_view(), name="entry-create"),
    path('entry/<int:pk>/', EntryDetail.as_view(), name="entry-detail"),
    path('entry/<int:pk>/update/',
         EntryUpdate.as_view(), name="entry-update"),
    path('entry/<int:pk>/delete/',
         EntryDelete.as_view(), name="entry-delete"),
    path('tags/<pk>',
         TagList.as_view(), name="tag-list"),
    path('tools/climate_data_finder/',
         ClimateScrapeCreate.as_view(), name="climate-scrape"),
    path('tools/climate_data_finder/results/<pk>/',
         ClimateScrapeResults.as_view(), name="climate-scrape-results"),
    path('tools/climate_data_finder/output/<station_ID>/<start_year>/<end_year>/',
         ClimateScrapeExport, name="climate-scrape-export"),
    path('tools/climate_data_finder/output/max/<station_ID>/<start_year>/<end_year>/',
         ClimateScrapeAnnualMaxPrecip, name="climate-scrape-annual-max-precip"),
    path('donation-checkout/', DonateCheckout, name="donate-checkout"),
    path('payment-success/<pk>/', PaymentSuccess.as_view(), name="payment-success"),
    path('dataviz/<viz_url>/', DataVizDetail.as_view(), name="dataviz-test")

]  # + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dkht/forms.py
from django import forms
from django.utils import timezone
from .models import Entry, StationSearchTarget, Donation  # , EntryImage

#from markdownx.fields import MarkdownxWidget


class EntryForm(forms.ModelForm):

    def save(self, commit=True):
        self.instance.entry = self.entry

        return super().save(commit)

    class Meta:
        model = Entry
        fields = ('post_type', 'title', 'byline',
                  'text_body', 'image', 'tags', 'video')

    def __init__(self, *args, **kwargs):
        # Call to ModelForm constructor
        super(EntryForm, self).__init__(*args, **kwargs)
        self.fields['text_body'].widget.attrs['height'] = '50vh'


class ClimateScrapeForm(forms.ModelForm):

    def save(self, commit=True):
        self.instance.stationsearchtarget = self.stationsearchtarget
        return super().save(commit)

    class Meta:
        model = StationSearchTarget
        fields = ['lat', 'lon', 'search_radius']

    def __init__(self, *args, **kwargs):
        # Call to ModelForm constructor
        super(ClimateScrapeForm, self).__init__(*args, **kwargs)

    # def __init__(self, *args, **kwargs):
    #     # Call to ModelForm constructor
    #     super(ClimateScrapeForm, self).__init__(*args, **kwargs)
    #

#
# class EntryImageForm(forms.ModelForm):
#
#     def save(self, commit=True):
#         self.instance.entryimage = self.entry
#         return super().save(commit)
#
#
#     class Meta:
#         model = EntryImage
#         fields = ('image',)

dkht/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.views.generic.edit import FormView, UpdateView, CreateView, DeleteView
from django.views.generic import ListView, View, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView, SingleObjectMixin
from .models import Entry, StationSearchTarget, ClimateStation, Donation
from .forms import EntryForm, ClimateScrapeForm
from django.urls import reverse_lazy, reverse
from django.conf import settings
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.utils import timezone
from django.db import transaction
from django.forms.models import inlineformset_factory

from io import StringIO

from bokeh.embed import server_session
from bokeh.util import session_id

from climatescrape import station_search


import logging
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


class Main(TemplateView):
    """
    View for default landing page.
    """
    template_name = 'dkht/frontpage.html'


class Contact(TemplateView):
    """
    View for default landing page.
    """
    template_name = 'dkht/contact.html'


class PaymentSuccess(TemplateView):
    """
    View for successful payment.
    """
    model = Donation
    template_name = 'dkht/payment-success.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        print('transaction object pk = ', self.kwargs['pk'])
        context['donation'] = get_object_or_404(
            Donation, charge_id=self.kwargs['pk'])
        return context


class EntryList(ListView):
    """
    View for Project Entries (Work Portfolio List view)
    """
    model = Entry

    # def get_context_data(self, *args, **kwargs):
    #     context = super()

    def get_queryset(self):
        qs = super().get_queryset()
        qs = Entry.objects.order_by('-created')
        return qs


class EntryCreate(LoginRequiredMixin, CreateView):
    """
    Will need to change implementation of stations once
    organization and user are incorporated.
    """
    model = Entry
    fields = ['post_type', 'title', 'byline',
              'text_body', 'image', 'tags', 'video']

    def get_context_data(self, *args, **kwargs):
        context = super(EntryCreate, self).get_context_data(**kwargs)
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('dkht:entry-list')

    def form_valid(self, form):
        # form.save(commit=True)
        return super(EntryCreate, self).form_valid(form)


class EntryDetail(DetailView):
    model = Entry

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        context['entry'] = get_object_or_404(Entry, id=self.kwargs['pk'])
        return context


class EntryUpdate(LoginRequiredMixin, UpdateView):
    """
    Will need to change implementation of stations once
    organization and user are incorporated.
    """
    model = Entry
    fields = ['post_type', 'title', 'byline',
              'text_body', 'image', 'tags', 'video']

    def get_context_data(self, *args, **kwargs):
        context = super(EntryUpdate, self).get_context_data(**kwargs)
        context['entry'] = get_object_or_404(Entry, id=self.kwargs['pk'])
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('dkht:entry-detail', kwargs={
            'pk': self.kwargs['pk'],
        })


class EntryDelete(LoginRequiredMixin, DeleteView):
    """
    Will need to change implementation of stations once
    organization and user are incorporated.
    """
    model = Entry

    def get_success_url(self, *args, **kwargs):
        return reverse_lazy('dkht:entry-list')


class TagList(ListView):
    """
    Possibly redundant view.
    """
    model = Entry

    # def get_context_data(self, *args, **kwargs):
    #     context = super()

    def get_queryset(self):
        qs = super().get_queryset()
        # if self.request.user
        tag = self.kwargs['pk']
        qs = Entry.objects.filter(tags__contains=tag).order_by('created')
        return qs


class ClimateScrapeCreate(CreateView):
    model = StationSearchTarget
    template_name = "dkht/climatescrape_form.html"
    fields = ['lat', 'lon', 'search_radius']

    def get_context_data(self, *args, **kwargs):
        context = super(ClimateScrapeCreate, self).get_context_data(**kwargs)
        context['stripe_key'] = settings.STRIPE_PUBLIC_KEY
        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('dkht:climate-scrape-results', kwargs={'pk': self.object.id, })

    def form_valid(self, form):
        return super(ClimateScrapeCreate, self).form_valid(form)


class ClimateScrapeResults(DetailView):
    model = StationSearchTarget
    template_name = "dkht/climatescrape_list.html"
    fields = ['lat', 'lon', 'search_radius']

    def get_context_data(self, *args, **kwargs):
        context = super(ClimateScrapeResults, self).get_context_data(**kwargs)
        target = get_object_or_404(
            StationSearchTarget, id=self.kwargs['pk'])

        results = station_search.get_stations(
            target.lat, target.lon, target.search_radius)

        # now convert the output stations to a context object
        # that can be used in the templateview
        stations = []
        if len(results) > 0:
            for station in results:
                st = ClimateStation(**station)
                stations += [st]
            context['stations'] = stations
        else:
            context['stations'] = None

        context['stripe_key'] = settings.STRIPE_PUBLIC_KEY

        return context

    def get_success_url(self, **kwargs):
        return reverse_lazy('dkht:climate-scrape-results', kwargs={'pk': self.object.id, })

    def form_valid(self, form):
        # form.save(commit=True)

        return super(ClimateScrapeResults, self).form_valid(form)


def ClimateScrapeExport(request, station_ID, start_year, end_year):
    # def get(self, request), station_ID, start_year, end_year):
    # stn_id = request.GET.get('station_ID')
    # start_year = request.GET.get('start_year')
    # end_year = request.GET.get('end_year')
    # Create the HttpResponse object with the appropriate CSV header.

    data, filename = station_search.make_dataframe(
        station_ID, start_year, end_year)

    buff = StringIO()

    output = data.to_csv(buff, index=None)

    buff.seek(0)

    response = HttpResponse(buff, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename={}'.format(
        filename)

    return response


def ClimateScrapeAnnualMaxPrecip(request, station_ID, start_year, end_year):
        # def get(self, request), station_ID, start_year, end_year):
    # stn_id = request.GET.get('station_ID')
    # start_year = request.GET.get('start_year')
    # end_year = request.GET.get('end_year')
    # Create the HttpResponse object with the appropriate CSV header.

    data, filename = station_search.make_dataframe(
        station_ID, start_year, end_year)

    try:
        annual_max_precip_data = station_search.extract_annual_max_precip(data)
        buff = StringIO()

        output = annual_max_precip_data.to_csv(buff, index=None)

        buff.seek(0)

        response = HttpResponse(buff, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename={}'.format(
            filename)

        return response
    except ValueError as error:
        html = "<html><body>Error parsing MSC data. {}</body></html>".format(
            error)
        return HttpResponse(html)


class DataVizDetail(TemplateView):
    model = Entry
    template_name = "dkht/bokeh_post.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        data_viz_id = context['viz_url']
        dataviz_url = self.request.build_absolute_uri(
            location='/') + context['viz_url']
        print('')
        print('dataviz url = ', dataviz_url)
        print('')
        try:
            bk_script = server_session(
                None, session_id=session_id.generate_session_id(), url=dataviz_url)
            context['bk_script'] = bk_script
        except Exception as e:
            msg = "Uh oh.  Richard, whatja do??: {}".format(e)
            logger.error(msg)

        return context

templates/dkht/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-122017653-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag() { dataLayer.push(arguments); }
		gtag('js', new Date());

		gtag('config', 'UA-122017653-1');
	</script>

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
	<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
	<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
	 crossorigin="anonymous"></script>
	<title>DK Hydro / tech - Multi-disciplinary Data Analysis and Hydrotechnical Engineering</title>
</head>

<body>
	{% block javascript %}
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
	<script type="text/javascript" src="{% static 'js/dkht.js' %}"></script>
	{% endblock javascript %}

	{% block navcontent %}

	<!-- Dropdown Structure -->

	<ul id="dropdown1" class="dropdown-content">
		<li>
			<a href="{% url 'dkht:climate-scrape' %}">Climate Data Wrangler</a>
		</li>

	</ul>
	<ul id="dropdown2" class="dropdown-content">
		<li>
			<a href="{% url 'dkht:climate-scrape' %}">Climate Data Wrangler</a>
		</li>

	</ul>

	<nav class="grey lighten-3">
		<div class="nav-wrapper">

			<a href="{% url 'dkht:main-view' %}" class="brand-logo svg-logo-wrapper hide-on-med-and-down">
				<img src="{% static 'images/dkhydrotech1.3.1.svg' %}" class="shadow ">
			</a>
			<a href="{% url 'dkht:main-view' %}" class="brand-logo hide-on-small-only grey-text text-darken-3 left" style="margin-left: 75px;">DK
				HYDROTECH</h4>
				<a href="{% url 'dkht:main-view' %}" class="brand-logo hide-on-med-and-up grey-text text-darken-3 right">DK
					HYDROTECH</h4>


					<ul class="right hide-on-med-and-down">
						{% if user.is_authenticated %}
						<li>
							<a href="{% url 'dkht:entry-create' %}">
								<i class="material-icons left">add</i>CONTENT</a>
						</li>
						{% endif %}
						<li>
							<a class="dropdown-button" href="#!" data-activates="dropdown2">TOOLS
								<i class="material-icons right">arrow_drop_down</i>
							</a>
						</li>
						<li>
							<a href="{% url 'dkht:entry-list' %}">PROJECTS</a>
						</li>
						<li>
							<a href="{% url 'dkht:contact-view' %}">CONTACT</a>
						</li>
					</ul>

					<ul class="side-nav" id="mobile-demo">
						<li>
							<a href="{% url 'dkht:main-view' %}">HOME</a>
						</li>
						<li>
							<a class="dropdown-button" href="#!" data-activates="dropdown1">TOOLS
								<i class="material-icons right">arrow_drop_down</i>
							</a>
						</li>
						<li>
							<a href="{% url 'dkht:entry-list' %}">PROJECTS</a>
						</li>
						<li>
							<a href="{% url 'dkht:contact-view' %}">CONTACT</a>
						</li>
						{% if user.is_authenticated %}
						<li>
							<a href="{% url 'dkht:entry-create' %}" class="grey-text text-darken-2">
								<i class="material-icons left">add</i>CONTENT</a>
						</li>
						{% endif %}
					</ul>

					<a href="#" data-activates="mobile-demo" class="button-collapse">
						<i class="material-icons">menu</i>
					</a>

		</div>
	</nav>


	{% endblock navcontent %}

	{% block content %}{% endblock content %}

	<footer class="page-footer grey lighten-3">
		<div class="container">
			<div class="row">
				<div class="col s12 m4 center">
					<span class="flow-text">
						<a href="https://github.com/dankovacek" class="social">GITHUB</a>
					</span>
				</div>
				<div class="col s12 m4 center">
					<span class="flow-text">
						<a href="https://www.linkedin.com/in/dankovacek/" class="social">LINKEDIN</a>
					</span>
				</div>
				<div class="col s12 m4 center">
					<span class="flow-text">
						<a href="https://google.com/+DanKovacek" class="social">GOOGLE +</a>
					</span>
				</div>
			</div>
		</div>
		<div class="footer copyright">
			<div class="container">
				<div class="col 16 s12 center license">
					<span class="flow-text">
						<h6>
							<a href="#">COPYRIGHT &#9400; 2017 DK Hydrotech. Vancouver, B.C. </a>
						</h6>
					</span>
				</div>
			</div>
		</div>
	</footer>

	<div id="code">
		[base64]
	</div>

	<script>
		// Encode an SVG element as a base64 data uri.
		function svgToBase64Image(svgElement) {
			var div = document.createElement('div');
			div.appendChild(svgElement.cloneNode(true));
			var b64 = window.btoa(div.innerHTML);
			return 'data:image/svg+xml;base64,' + b64;
		}
		var svgs = document.getElementsByTagName('svg');
		var urls = [];
		for (var i = 0; i < svgs.length; i++)
			urls.push('url("' + svgToBase64Image(svgs[i]) + '")');
		var url = urls.join(',');
		var msg = 'Base64 CSS image (for cross-browser support):' +
			'<br><br>background: ' + url + ';';
		document.getElementById('code').innerHTML = msg;
		document.body.style.background = url;
	</script>

</body>

</html>

templates/dkht/bokeh_post.html
{% extends 'dkht/base.html' %}
{% load static %}
{% load bokeh %}

{% load embed_video_tags %}

{% block head %}
    {{ block.super }}
    {% bokeh_css %}
{% endblock head %}

{% block content %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/post_markdown.js' %}"></script>

    <div id="background-image">
        <div class="container">
            <div class="row">
                {% if bk_script %}
                  <div class="col s12">
                    {{ bk_script|safe }}
                  </div>
                {% else %}
                  <div class="col s12">
                    <h4>No bokeh script passed</h4>
                  </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    {% bokeh_js %}
{% endblock javascripts %}

templates/dkht/climatescrape_form.html
{% extends "dkht/base.html" %}
{% load static %}
{% block content %}
{{ block.super }}

<div id="background-image">
  <div class="row">
    <div class="col s12">
      <h3>Canadian Climate Data Wrangler</h3>
      <h4>Search and Acquire Formatted Historical Climate Data</h4>
      <blockquote class="subheader flow-text"><em>2018-10-04 Added Feature: </em> Download the annual maximum
        daily precipitation series!</blockquote>
      <p class="subheader flow-text">Enter the lat/lon (in decimal degrees),
        choose a search radius, and submit. Note that your <em>longitude should be negative</em>.
        E.g. Vancouver, BC is located at 49.25, -123.12.
        The code will return all stations within
        the specified search radius from the target location. Results of the search
        are summarized in the subsequent view where you can download the resultant
        measured records in their entirety.</p>
    </div>
  </div>
  <div class="row">
    <div class="col s12 m8 push-m2 l6 push-l3 green lighten-4">
      <div class="row">
        <div class="col s12">
          <h5 class="flow-text">Search Parameters</h5>
          <form action="{{ action }}" method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn green darken-2 waves-effect waves-light" onclick="Materialize.toast('Search Submitted!', 4000)">Submit</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <p class="flow-text">The largest search
        radius is currently set to 50km, and the available frequency is limited to daily records.
        If you'd like a custom query, either for a larger search area, for hourly climate data, or for any other
        large
        data manipulation tasks, feel free to <a href="{% url 'dkht:contact-view' %}">contact me</a>.
        I can also be reached via the LinkedIn, Github, and Google+ links in the footer.</p>
    </div>
  </div>

  {% block payment %}
  {% include 'dkht/donation-form.html' %}
  {% endblock payment %}

</div>

{% endblock content %}

templates/dkht/climatescrape_list.html
{% extends "dkht/base.html" %}
{% load static %}
{% block content %}
{{ block.super }}

<div id="background-image">
  <div class="row">
    <div class="col s12">
      <h3>Canadian Climate Data Wrangler</h3>
      <div class="row">
        <div class="col s12">

          <blockquote>
            <h5><strong>NEW!</strong> Download the annual maximum daily precipitation series for any MSC climate
              station. Note that this is not the maximum 24-hour period, rather it is the 00:00 to 23:59 daily total.</h3>
          </blockquote>

          <p class="flow-text">
            Download the entire historical record for the stations found within your search radius.
          </p>

          <p class="flow-text">
            The largest search
            radius is currently set to 50km, and the available frequency is limited to daily records.
            If you'd like a custom query, either for a larger search area, for hourly climate data, or for any other
            large
            data manipulation tasks, feel free to <a href="{% url 'dkht:contact-view' %}">contact me</a>.
            I can also be reached via the LinkedIn, Github, and Google+ links in the footer.</p>
        </div>
      </div>
      <h4>Results</h4>
      {% if stations %}
      <table class="highlight">
        <thead>
          <tr>
            <th>Station Name</th>
            <th>Station ID</th>
            <th>Lat/Lon [dec. degrees]</th>
            <th>Distance to Target [km]</th>
            <th>Record Start Year</th>
            <th>Record End Year</th>
            <th>Download [daily]</th>
            <th>Download Annual Max. Precip.</th>
          </tr>
        </thead>
        <tbody>
          {% for station in stations %}
          <tr>
            <td>{{ station.station_name }}</td>
            <td>{{ station.station_ID }}</td>
            <td>{{ station.latlon }}</td>
            <td>{{ station.distance_to_target|floatformat:1 }}</td>
            <td>{{ station.start_year }}</td>
            <td>{{ station.end_year }}</td>

            <td>
              <a href="{% url 'dkht:climate-scrape-export' station_ID=station.station_ID start_year=station.start_year end_year=station.end_year %}">
                <i class="material-icons tooltipped" data-position="left" data-tooltip="Download climate data for the entire period of record.">cloud_download</i>
              </a>
            </td>
            <td>
              <a href="{% url 'dkht:climate-scrape-annual-max-precip' station_ID=station.station_ID start_year=station.start_year end_year=station.end_year %}">
                <i class="material-icons tooltipped" data-position="left" data-tooltip="Download the annual maximum precipitation for the entire period of record.">play_for_work</i>
              </a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p class="subheader">No stations found. <a href="{% url 'dkht:climate-scrape' %}">Try a larger search radius or
          another location.</a></p>
      {% endif %}
    </div>
  </div>

  {% block payment %}
  {% include 'dkht/donation-form.html' %}
  {% endblock payment %}

  <!-- Stripe Donation Link -->
  {% endblock content %}

templates/dkht/contact.html
{% extends 'dkht/base.html' %}
{% load static %}
{% block content %}


{{ block.super }}
<div id="index-banner" class="parallax-container hide-on-small-only">

  <div class="section no-pad-bot">
    <div class="container">
    </div>
  </div>

  <div class="parallax">
    <img src="{% static 'images/sub-zero_water.JPG' %}" alt="Unsplashed background img 1">
  </div>

</div>

<div id="background-image">
    <div class="container-fluid">
      <br>
        <div class="row valign-wrapper">

            <div class="col s4 m3 l3 push-l1">
                <div class="img-logo">
                    <img src="{% static 'images/dkhydrotech1.3.1.svg' %}" class="shadow responsive-img">
                </div>
            </div>

            <div class="col s6 m5 pull-m2 pull-l1">
                <h4 class="green-text text-darken-4">Dan Kovacek, P.Eng.</h4>
                <ul class="contact-list grey-text text-darken-4">
                    <li>Data Analysis</li>
                    <li>Fullstack Development</li>
                    <li>Hydrotechnical Engineering</li>
                    <li>dan@dkhydrotech.com</li>
                    <li>Vancouver, BC</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div id="index-banner" class="parallax-container hide-on-small-only">
  <div class="section no-pad-bot">
    <div class="container">

    </div>
  </div>
  <div class="parallax">
    <img src="{% static 'images/seed_peak.jpg' %}" alt="Unsplashed background img 1">
  </div>
</div>

{% if user.is_authenticated %}
<div class="row">
    <div class="col s12">
        <div class="add-btn">
            <a class="waves-effect waves-light btn grey darken-3 white-text text-lighten-2" href="{% url 'dkht:entry-create' %}">
                <i class="material-icons right">add</i>Content
            </a>
        </div>
    </div>
</div>
{% endif %}

{% endblock content %}

templates/dkht/entry_detail.html
{% extends 'dkht/base.html' %}
{% load static %}
{% load embed_video_tags %}


{% block content %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'js/post_markdown.js' %}"></script>

    <div id="background-image">
        <div class="container">
            <!-- START VIDEO LAYOUT -->
            {% if entry.type == 'video' %}
                {%  if entry.video %}
                    <div class="row">
                        <div class="col s12 m10 push-m1">
                            <div class="video-container">
                                {% video entry.video %}
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% else %}
            <!-- END VIDEO LAYOUT -->

            <div class="row">
                <div class="col s12 light-green-text text-darken-3">
                    <h3>{{ entry.title }}</h3>
                </div>

                <!-- START PHOTO/BLEG/ILLUSTRATION LAYOUT -->
                {% if entry.image %}
                    <div class="row">
                        <div class="col s12 m10 push-m1 center-align">
                            <img class="responsive-img main-img" src="{{ entry.image.url }}">
                        </div>
                    </div>
                {% endif %}

                <div class="col s12 m10 push-m1">
                    <blockquote class="flow-text light-green-text text-darken-3">
                        {{ entry.byline }}
                    </blockquote>
                </div>

                {% if bk_script %}
                <div class="row">
                  <div class="col s12">

                    {{ bk_script|safe }}
                  </div>
                </div>
                {% else %}
                {% endif %}

                <div class="col s12 m10 push-m1">
                    {% if entry.text_body %}
                        <p class="flow-text">
                            {{ entry.formatted_markdown|safe }}
                        </p>
                    {% endif %}
                </div>

                <div class="col s12 m10 push-m1">
                    <h5 class="right light-green-text text-darken-3">Posted: {{ entry.created.date }}</h5>
                </div>
            </div>

            <div class="row">
                <div class="col s12 m10 push-m1">
                    {% if entry.tags %}
                        {% for tag in entry.tags_as_list %}
                            <div class="chip light-green lighten-2 hoverable">
                                <a href="{% url 'dkht:tag-list' pk=tag %}" class="grey-text text-darken-3 ">{{ tag }}</a>
                            </div>
                        {% endfor %}
                    {% endif %}

                </div>
            </div>
            {% if  user.is_authenticated %}
                <div class="row">
                    <div class="col s6 center">
                        <a href="{% url 'dkht:entry-update' pk=entry.id %}">
                            <i class="material-icons medium light-green-text text-darken-2">edit</i></a>
                    </div>
                    <div class="col s6 center">
                        <a href="{% url 'dkht:entry-delete' pk=entry.id %}">
                            <i class="material-icons medium light-green-text text-darken-2">delete</i></a>
                    </div>
                </div>
            {% endif %}
          {% endif %}
        </div>
    </div>

{% endblock content %}